// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeXl6ATUexIuwYOcUoHovG7Mn0DWmRdCY',
    appId: '1:396051261740:web:620fdc8ebb3d82a42ae489',
    messagingSenderId: '396051261740',
    projectId: 'assignment-flutter-recipe-app',
    authDomain: 'assignment-flutter-recipe-app.firebaseapp.com',
    storageBucket: 'assignment-flutter-recipe-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6uZiM-2ViYX8eMzkmGGKtcKBFd3IpG6o',
    appId: '1:396051261740:android:5a4375754cfda2632ae489',
    messagingSenderId: '396051261740',
    projectId: 'assignment-flutter-recipe-app',
    storageBucket: 'assignment-flutter-recipe-app.firebasestorage.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXMbbRKTKXJ6odoGttFU-O5vhU0-tjf28',
    appId: '1:396051261740:ios:729c2eb82f1da1682ae489',
    messagingSenderId: '396051261740',
    projectId: 'assignment-flutter-recipe-app',
    storageBucket: 'assignment-flutter-recipe-app.firebasestorage.app',
    iosBundleId: 'com.example.megaAssignmentFlutterRecipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeXl6ATUexIuwYOcUoHovG7Mn0DWmRdCY',
    appId: '1:396051261740:web:295b6c51f1afa7db2ae489',
    messagingSenderId: '396051261740',
    projectId: 'assignment-flutter-recipe-app',
    authDomain: 'assignment-flutter-recipe-app.firebaseapp.com',
    storageBucket: 'assignment-flutter-recipe-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXMbbRKTKXJ6odoGttFU-O5vhU0-tjf28',
    appId: '1:396051261740:ios:729c2eb82f1da1682ae489',
    messagingSenderId: '396051261740',
    projectId: 'assignment-flutter-recipe-app',
    storageBucket: 'assignment-flutter-recipe-app.firebasestorage.app',
    iosBundleId: 'com.example.megaAssignmentFlutterRecipeApp',
  );
}
